version: '3.3'

volumes:
  foodgram_pg_data:
  foodgram_static:
  foodgram_media:

services:
  db:
    image: postgres:13.10
    env_file: ../.env
    volumes:
      - foodgram_pg_data:/var/lib/postgresql/data
    restart: on-failure
    healthcheck:
      test: pg_isready -U foodgram
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    image: pressxtowin7/foodgram_backend
    env_file: ../.env
    volumes:
      - foodgram_static:/static
      - foodgram_media:/media
    depends_on:
      db:
        condition: service_healthy

  frontend:
    image: pressxtowin7/foodgram_frontend
    volumes:
      - foodgram_static:/static
    command: cp -r /app/build/. /static/

  nginx:
    image: nginx:1.19.3
    ports:
      - "9000:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - foodgram_static:/usr/share/nginx/html/
      - foodgram_media:/media
    depends_on:
      - backend